name: Deploy to Surge (Staging)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Surge Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Deps
        run: yarn
      - name: Build and Publish
        run: yarn deploy:staging
        env:
          SURGE_LOGIN: ${{ secrets.surge_login }}
          SURGE_TOKEN: ${{ secrets.surge_token }}
