# This is a basic workflow to help you get started with Actions

name: Deploy Main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Surge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn build
      - name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: "ddrdraw.surge.sh"
          project: "./dist"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
