name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  validate:
    name: Valid Song Data
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn --frozen-lockfile
    - run: yarn validate
